[package]
name = "rust_game"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.15.0"

[features]
vulkan = ["amethyst/vulkan"]
# empty = ["amethyst/empty"]
# metal = ["amethyst/metal"]
